// apps/api/src/native/native-hooks.ts
// The two static files a native session's harness is launched with
// (docs/specs/2026-10-05-native-sessions.md). Both are passed as LAUNCH ARGUMENTS — claude's
// `--settings`, omp's `--hook` — and both only ADD to the user's own configuration, which is
// never written. Neither file holds a secret: the per-launch URL and bearer arrive in the
// harness's environment (KERMANYCH_NATIVE_URL / KERMANYCH_NATIVE_TOKEN), so every native
// session on this machine shares the same two files. Written once per api process to a fixed
// temp path, like runtime/omp-mcp-bridge.ts.
import { mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

export const NATIVE_URL_ENV = "KERMANYCH_NATIVE_URL";
export const NATIVE_TOKEN_ENV = "KERMANYCH_NATIVE_TOKEN";

// The hook events Kermanych reads a claude session's status from (native-session.service.ts).
export const CLAUDE_HOOK_EVENTS = [
  "SessionStart",
  "UserPromptSubmit",
  "PreToolUse",
  "PostToolUse",
  "PermissionRequest",
  "Notification",
  "Stop",
] as const;

// The hook's stdin (claude's JSON for the event) is forwarded verbatim. `-o /dev/null`
// matters: stdout of a `UserPromptSubmit`/`SessionStart` hook is added to the agent's context.
// `|| true` and no output mean the hook never blocks anything and never decides a
// `PermissionRequest`/`PreToolUse`. `-m 3` bounds a wedged api well inside the 5 s timeout.
export const CLAUDE_HOOK_COMMAND =
  `curl -sS -m 3 -o /dev/null -H "Authorization: Bearer $${NATIVE_TOKEN_ENV}" -H "Content-Type: application/json" ` +
  `--data-binary @- "$${NATIVE_URL_ENV}/claude" || true`;

export function claudeSettings(): { hooks: Record<string, { hooks: { type: "command"; command: string; timeout: number }[] }[]> } {
  const hooks: Record<string, { hooks: { type: "command"; command: string; timeout: number }[] }[]> = {};
  for (const event of CLAUDE_HOOK_EVENTS) hooks[event] = [{ hooks: [{ type: "command", command: CLAUDE_HOOK_COMMAND, timeout: 5 }] }];
  return { hooks };
}

// Plain ESM JavaScript: omp loads it with no build step. Inert unless both env vars are set
// (a hand-started omp that happens to load it does nothing), silent for subagents, and it can
// never throw into omp: every handler and every POST is caught. Posts are chained so the api
// receives `tool` before its `tool_end` even when a request is slow.
export const OMP_EXTENSION_SOURCE = `// Generated by Kermanych (apps/api/src/native/native-hooks.ts) — do not edit.
const url = process.env.${NATIVE_URL_ENV};
const token = process.env.${NATIVE_TOKEN_ENV};
let chain = Promise.resolve();

function post(body) {
  chain = chain
    .then(() =>
      fetch(url + "/omp", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: "Bearer " + token },
        body: JSON.stringify(body),
        signal: AbortSignal.timeout(3000),
      }),
    )
    .then(
      () => undefined,
      () => undefined,
    );
}

function lastAssistant(messages) {
  if (!Array.isArray(messages)) return undefined;
  for (let i = messages.length - 1; i >= 0; i--) if (messages[i] && messages[i].role === "assistant") return messages[i];
  return undefined;
}

export default function (pi) {
  if (!url || !token) return;
  const on = (name, fn) =>
    pi.on(name, (event, ctx) => {
      try {
        if (ctx && ctx.agent && ctx.agent.kind === "sub") return;
        fn(event || {}, ctx);
      } catch {}
    });
  const session = (ctx) => {
    const sm = ctx && ctx.sessionManager;
    if (!sm) return;
    const sessionFile = sm.getSessionFile && sm.getSessionFile();
    const sessionId = sm.getSessionId && sm.getSessionId();
    if (sessionFile || sessionId) post({ event: "session", sessionId, sessionFile });
  };
  on("session_start", (_e, ctx) => session(ctx));
  on("session_switch", (_e, ctx) => session(ctx));
  on("agent_start", (_e, ctx) => {
    session(ctx);
    post({ event: "working" });
  });
  on("tool_execution_start", (e) => post({ event: "tool", toolName: String(e.toolName || "") }));
  on("tool_execution_end", () => post({ event: "tool_end" }));
  on("tool_approval_requested", () => post({ event: "blocked" }));
  on("tool_approval_resolved", () => post({ event: "unblocked" }));
  on("agent_end", (e) => {
    const last = lastAssistant(e.messages);
    if (last && last.stopReason === "error") post({ event: "error", message: String(last.errorMessage || "") });
    else post({ event: "idle" });
  });
}
`;

// Rewritten on every launch rather than memoized: the content is tiny and fixed, and a temp
// directory the OS swept while the api ran must not leave a launch pointing at a missing file.
async function writeHookFile(name: string, content: string): Promise<string> {
  const dir = join(tmpdir(), "kermanych-native");
  await mkdir(dir, { recursive: true });
  const path = join(dir, name);
  await writeFile(path, content, "utf8");
  return path;
}

export function claudeSettingsPath(): Promise<string> {
  return writeHookFile("claude-settings.json", JSON.stringify(claudeSettings(), null, 2));
}

export function ompExtensionPath(): Promise<string> {
  return writeHookFile("omp-native.js", OMP_EXTENSION_SOURCE);
}
