// apps/api/src/runtime/omp-mcp-bridge.ts
// omp reads MCP servers only from config FILES (.omp/mcp.json in the working directory, or the
// user's profile), and the Менеджмент chat's working directory is the operator's own
// repository — writing a server into it would put a per-conversation secret into their tree.
// So the omp runtime is handed the same HTTP MCP server the claude runtime gets natively, via
// this tiny extension (`omp -e`): at load it asks the server for its tools and registers each
// as an omp tool whose execute is one `tools/call`. The URL and bearer arrive in the child's
// environment, never on disk.
//
// Extension tools survive `--tools read,grep,glob` (the list restricts built-ins only), and
// `loadMode: "essential"` keeps them top-level instead of behind omp's tool discovery.
import { mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

export const MCP_URL_ENV = "KERMANYCH_MCP_URL";
export const MCP_TOKEN_ENV = "KERMANYCH_MCP_TOKEN";

// Plain ESM JavaScript: omp loads it with no build step and no dependency on this package.
// A server that cannot be reached at load leaves the child without the tools rather than
// without a chat — the prompt states the tools, and the model then reports them unavailable.
const SOURCE = `// Generated by Kermanych (apps/api/src/runtime/omp-mcp-bridge.ts) — do not edit.
const url = process.env.${MCP_URL_ENV};
const token = process.env.${MCP_TOKEN_ENV};
let seq = 0;

async function rpc(method, params, signal) {
  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json", Accept: "application/json, text/event-stream", Authorization: "Bearer " + token },
    body: JSON.stringify({ jsonrpc: "2.0", id: ++seq, method, params }),
    signal,
  });
  if (!res.ok) throw new Error("Kermanych tools answered HTTP " + res.status);
  const msg = await res.json();
  if (msg.error) throw new Error(msg.error.message);
  return msg.result;
}

export default async function (pi) {
  if (!url || !token) return;
  let tools;
  try {
    await rpc("initialize", { protocolVersion: "2025-06-18", capabilities: {}, clientInfo: { name: "omp-kermanych-bridge", version: "1" } });
    tools = (await rpc("tools/list", {})).tools;
  } catch (err) {
    pi.logger?.warn?.("kermanych mcp bridge: " + (err && err.message));
    return;
  }
  for (const t of tools) {
    pi.registerTool({
      name: t.name,
      label: t.name,
      description: t.description,
      parameters: t.inputSchema,
      loadMode: "essential",
      // omp's extension signature: (toolCallId, params, signal, onUpdate, ctx). Text items are
      // joined into one; image items (the session browser's screenshot) pass through as omp
      // image content after it.
      async execute(_id, params, signal) {
        const r = await rpc("tools/call", { name: t.name, arguments: params ?? {} }, signal);
        const items = r.content ?? [];
        const text = items.filter((c) => c.type !== "image").map((c) => c.text ?? "").join("\\n");
        if (r.isError) throw new Error(text);
        const images = items.filter((c) => c.type === "image" && c.data).map((c) => ({ type: "image", data: c.data, mimeType: c.mimeType }));
        return { content: [...(text || !images.length ? [{ type: "text", text }] : []), ...images] };
      },
    });
  }
}
`;

let written: Promise<string> | undefined;

// Written once per api process to a fixed temp path; every omp child loads the same file.
export function ompMcpBridgePath(): Promise<string> {
  written ??= (async () => {
    const dir = join(tmpdir(), "kermanych-omp-mcp");
    await mkdir(dir, { recursive: true });
    const path = join(dir, "bridge.js");
    await writeFile(path, SOURCE, "utf8");
    return path;
  })().catch((err: unknown) => {
    written = undefined;
    throw err;
  });
  return written;
}
