// apps/ui/src/stores/risks.ts
import { defineStore } from 'pinia';
import { ref } from 'vue';
import type {
  ProjectRisk,
  ProjectRiskEvent,
  ProjectRiskInsert,
  ProjectRiskPatch,
} from '@kermanych/cloud';
import {
  createProjectRisk as cloudCreateRisk,
  listProjectRisks as cloudListRisks,
  listRiskEvents as cloudListRiskEvents,
  patchProjectRisk as cloudPatchRisk,
} from '@kermanych/cloud';
import { useAuth } from './auth';
import { useOrchestrator } from './orchestrator';
import { IS_PREVIEW } from '../lib/preview';

// The project risk register. Keyed by PROJECT rather than held as one flat list: the register
// is a screen you open for one project, and a shared list would flash the previous project's
// rows for the length of a fetch every time the sidebar selection changes.
//
// Deliberately no Realtime channel (the table is not in the supabase_realtime publication):
// a register is edited a handful of times a week by people who are looking at it, so a live
// socket would cost a connection to deliver almost nothing. The screen refetches on open.
export const useRisks = defineStore('risks', () => {
  const auth = useAuth();
  const local = useOrchestrator();

  const byProject = ref<Record<string, ProjectRisk[]>>({});
  // One risk's audit trail, fetched when its history is opened. Dozens of risks each carry a
  // history nobody is reading until they ask for it.
  const eventsByRisk = ref<Record<string, ProjectRiskEvent[]>>({});
  const loading = ref(false);
  // Inline on the screen, never a toast: an unreachable Supabase must not greet someone who
  // opened the register only to read it (same call as stores/board.ts).
  const loadError = ref<string | null>(null);

  function fail(e: unknown): void {
    local.notify(e instanceof Error ? e.message : String(e), 'error');
  }

  // Replace-or-append keyed by id, then re-sorted the way the cloud returns a fresh page, so
  // an edited row does not jump to the end of the table it was edited in.
  function upsert(projectId: string, risk: ProjectRisk): void {
    const rows = (byProject.value[projectId] ?? []).filter((r) => r.id !== risk.id);
    rows.push(risk);
    rows.sort((a, b) => b.exposure - a.exposure || a.code.localeCompare(b.code));
    byProject.value = { ...byProject.value, [projectId]: rows };
  }

  async function load(projectId: string): Promise<void> {
    await auth.ready;
    // A preview signs in against a cloudless api (lib/preview.ts): there is no Supabase
    // project behind it, so there is no register to read.
    if (IS_PREVIEW || !auth.user || !projectId) return;
    loading.value = true;
    loadError.value = null;
    try {
      byProject.value = { ...byProject.value, [projectId]: await cloudListRisks(auth.client, projectId) };
    } catch (e) {
      loadError.value = e instanceof Error ? e.message : String(e);
    } finally {
      loading.value = false;
    }
  }

  // Writes THROW; reads report inline. Two callers now write to this register — the editor
  // on the screen and the management assistant's action executor
  // (stores/management-chat.ts) — and they answer a failure differently: the editor stays
  // open with a toast, the chat prints the reason into the transcript as the line that says
  // the risk was NOT filed. A store that swallowed the error into a toast would leave the
  // chat with nothing to say but «не вдалося», which is the message an operator cannot act on.
  //
  // No optimistic row: `code` is minted by the trigger under a per-project advisory lock, so
  // the register's own identifier only exists once Postgres has answered. Showing R-??? for a
  // moment would be showing a number that is about to change.
  async function create(
    projectId: string,
    input: Omit<ProjectRiskInsert, 'projectId'>,
  ): Promise<ProjectRisk> {
    if (!auth.user) throw new Error('Спочатку увійдіть у Kermanych');
    const created = await cloudCreateRisk(auth.client, { projectId, ...input });
    upsert(projectId, created);
    return created;
  }

  // Optimistic writes are pointless here and would be wrong: `exposure`, `residualExposure`,
  // `emv` and `closedAt` are generated by Postgres, so a locally patched row would show the
  // OLD severity beside the new scores until the response landed. The editor stays busy
  // instead, and the row arrives complete.
  async function save(
    projectId: string,
    id: string,
    patch: ProjectRiskPatch,
  ): Promise<ProjectRisk> {
    const saved = await cloudPatchRisk(auth.client, id, patch);
    upsert(projectId, saved);
    // The history changed with the row, so a cached copy would be a lie the next time the
    // «Історія» tab opens. Drop it rather than guess what the trigger recorded.
    const next = { ...eventsByRisk.value };
    delete next[id];
    eventsByRisk.value = next;
    return saved;
  }

  // The review cadence, recorded. This is the one audit column a client may write, and only
  // to «now»: the trigger files it as a `reviewed` event, which is what turns «we review
  // weekly» into something a phase gate can check.
  //
  // The one write that reports its own failure, because it is the one write with no form and
  // no transcript behind it: a row's «переглянуто» button takes no input, so there is nothing
  // for a caller to keep open and nothing better to say than the toast.
  async function markReviewed(projectId: string, id: string): Promise<ProjectRisk | undefined> {
    try {
      return await save(projectId, id, { lastReviewedAt: new Date().toISOString() });
    } catch (e) {
      fail(e);
      return undefined;
    }
  }

  async function loadEvents(riskId: string): Promise<void> {
    if (IS_PREVIEW || !auth.user || eventsByRisk.value[riskId]) return;
    try {
      eventsByRisk.value = {
        ...eventsByRisk.value,
        [riskId]: await cloudListRiskEvents(auth.client, riskId),
      };
    } catch (e) {
      fail(e);
    }
  }

  return { byProject, eventsByRisk, loading, loadError, load, create, save, markReviewed, loadEvents };
});
